Ignore RuntimeErorr at shutdown caused by logging
The error message is this for reference:
```
RuntimeError: wrapped C/C++ object of type ErrorHandler has been deleted
```